4.13. Обратная сторона реальности
htmlacademy-react/169447-six-cities-9 pull request #5
Opened 2022-02-23 19:04 UTC by ikashyntseva

2022-02-26 13:24 UTC, what1s1ove requested changes

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/favorite-button/favorite-button.tsx
> +    // width="18" height="19"
```suggestion
```

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/host/host.tsx
> +import {generateId} from '../../mocks/offers';
```suggestion
import { generateId } from '../../mocks/offers';
```
где-то есть спейсы,где-то нету

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/host/host.tsx
> +        {description.map((text, idx) =>(<p key={generateId()} className="property__text">{text}</p>))}
```suggestion
        {description.map((text) =>(<p key={idx.toString()} className="property__text">{text}</p>))}
```
лучше так

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/locations-list/locations-list.tsx
>              }
```suggestion
              const isActive = location === activeLocation;
```

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/offers-list/offers-list.tsx
> +  const [activeOfferCard, setActiveOfferCard] = useState('');
```suggestion
  const [activeOfferCard, setActiveOfferCard] = useState<string>('');
```
всегда типизируй стейты. И лучше сюда

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/property-facilities/property-facilities.tsx
> +          <li key={generateId()} className="property__inside-item">
лучше idx

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/property-facilities/property-facilities.tsx
>          {facilities.map((facility, idx) => (
не пойму почему линтер не отрабатывает) должно быть много ошибок) Как минимум, сейчас переменная idx не используется

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/reviews-form/reviews-form.tsx
> +  const [reviewData, setReviewData] = useState({
затипизируй 👍

2022-02-26 13:24 UTC, what1s1ove commented on project/src/components/reviews-form/reviews-form.tsx
> +    userName,
```suggestion
```
этого в оффере быть не должно. имя будет браться с авторизации автоматом. там только сам отзыв и райтинг

2022-02-26 13:24 UTC, what1s1ove commented on project/src/pages/main/main.tsx
> +  const locationOffers = useMemo(() => offers.find((offer) => offer.location === activeLocation)?.offers || [], [offers, activeLocation]);
```suggestion
  const locationOffers = useMemo(() => offers.find((offer) => offer.location === activeLocation)?.offers ?? [], [offers, activeLocation]);
```

2022-02-26 13:24 UTC, what1s1ove commented on project/src/pages/room/room.tsx
> +  const info = offers.find((offer) => offer.id === id) || offers[0];
```suggestion
  const [defaultOffer] = offers;
  const info = offers.find((offer) => offer.id === id) ?? defaultOffer;
```

2022-02-26 13:24 UTC, what1s1ove commented on project/src/pages/room/room.tsx
> +  const id = useLocation().pathname.replace('/offer/', '');
используй хук `useParams`

2022-02-26 13:24 UTC, what1s1ove commented on project/src/types/offer.ts
> +export type Offers = Offer[] | []
```suggestion
export type Offers = Offer[]
```
одно и то же

2022-02-26 13:24 UTC, what1s1ove commented on project/src/types/offer.ts
> +export type LocationOffers = LocationOffer[] | []
```suggestion
export type LocationOffers = LocationOffer[]
```

2022-02-27 16:26 UTC, ikashyntseva commented on project/src/components/locations-list/locations-list.tsx
>              }
что-то я пропустила такое

2022-02-28 06:50 UTC, what1s1ove approved these changes

2022-02-28 06:50 UTC, merged